version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/envelope_api_client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/envelope_local_storage"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/account_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/auth_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/budget_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/envelope_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/goal_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/notification_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/report_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/sharing_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/subscription_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/sync_repository"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/transaction_repository"
    schedule:
      interval: "weekly"
