name: account_repository
description: Account repository for Envelope.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  drift: ^2.26.0
  envelope_api_client:
    path: ../envelope_api_client
  envelope_local_storage:
    path: ../envelope_local_storage
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.9.0

dev_dependencies:
  build_runner: ^2.4.0
  freezed: ^4.0.0-dev.3
  json_serializable: ^6.9.0
  mocktail: ^1.0.0
  test: ^1.31.2
  very_good_analysis: ^10.2.0
