// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahMTfGYG2-z-y7ePyb40GE0nBi20GU9M',
    appId: '1:767046810526:web:2803b28b45b27c787b748f',
    messagingSenderId: '767046810526',
    projectId: 'white-board-3',
    authDomain: 'white-board-3.firebaseapp.com',
    storageBucket: 'white-board-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16GwJg6lKafy_rONOLezg4KTeEGSHFNo',
    appId: '1:767046810526:android:804ccc37f74d7c6e7b748f',
    messagingSenderId: '767046810526',
    projectId: 'white-board-3',
    storageBucket: 'white-board-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUcMHc7ThJf6XrCDjnSpNL_t7n9GkJ288',
    appId: '1:767046810526:ios:15a5063fe6b4ad5d7b748f',
    messagingSenderId: '767046810526',
    projectId: 'white-board-3',
    storageBucket: 'white-board-3.firebasestorage.app',
    iosBundleId: 'com.envelope.ml',
  );

}